### PR TITLE
Show local date and time when enabled

### PR DESCRIPTION
**Pull request by ahmetemir**
Adds local date and time at the top of login screen
#31 
datetime_added

### CODE REVIEW

**Comment by divVerent** [comment]
Thanks, looking already good - please fix the one (minor) issue and I'll merge it!

**Comment by ahmetemir** [comment]
I think you mean the issue about having _**show_datetime**_ larger than 1. If so, it is fixed.

**Comment by divVerent** [comment]
No, show_datetime != 1 wasn't actually the problem. I'm going to fix it myself - please look at the fix commit to learn from it. Thanks!

**Comment by divVerent** [comment]
Thanks, merged; see cc146ed9e6eff40413a616389b1caa8980add3bb for what needed to be fixed.

**Comment by divVerent** [comment]
Your commit became 177d5b264ff52bd775c981a64f77d463a4d505e6.

**Pull request closed without merging**
