### PR TITLE
Make it easier to show an image slideshow with saver_mpv.

### PR DESCRIPTION
**Pull request by dseomn**
I looked into applying the same changes to saver_mplayer, but I didn't see an easy way to change the image duration in mplayer.

### CODE REVIEW

**Comment by divVerent** [comment]
I really disagree with looping the playlist, as that means files not chosen due to the size limit will never be shown. However we can make the playlist longer to make the black screen situation very unlikely.

We could also length extend the playlist if it is too short (not enough pictures to fill a whole day), so we no longer pass, say, up to 4096 entries, but always exactly 4096.

For now the playlist length is rather low using very conservative assumptions about memory needs for a playlists.

**Comment by dseomn** [comment]
What about running mpv in a `while true; do ... | mpv ...; sleep 1; done &` loop? I'd be happier with the black screen at the end of the playlist if it lasted only about a second, and that seems simpler than extending a short playlist.

**Comment by divVerent** [comment]
Why even the sleep 1?

while run_mpv_once; do :; done

where run_mpv_once is a function that contains our current pipeline to generate a playlist and play it back.

On failure, we then still exit (so no worries about a "forkbomb" from failures), but we don't sleep during normal operation.

**Comment by dseomn** [comment]
The `sleep 1` prevents spinning if mpv finishes right away a status of zero. An empty playlist could cause that:

```
: | mpv --no-input-terminal --really-quiet --no-stop-screensaver --no-audio --image-display-duration=1 --shuffle --playlist=-; echo $?
0
```

(Something like "sleep until at least 1 second after mpv started" would be a better solution to that problem without affecting the typical case, but I don't know how to implement that in POSIX shell.)

**Comment by dseomn** [comment]
> (Something like "sleep until at least 1 second after mpv started" would be a better solution to that problem without affecting the typical case, but I don't know how to implement that in POSIX shell.)

Never mind, I do know how to implement that:
```shell
mpv &
mpv_pid=$!
sleep 1
wait $mpv_pid
```

**Comment by divVerent** [comment]
In fact, can even do:

mpv ... &
sleep 1
wait

I wouldn't bother making this more complicated than needed, as waiting for
all direct child processes is correct in most applications too (there
simply is no other).

**Comment by dseomn** [comment]
Cool, I didn't know about `wait` without arguments. I made the changes.

**Comment by divVerent** [comment]
This should work, so merging it.

**Pull request merged**
